### ISSUE TITLE
안녕하세요 질문드립니다.

### ISSUE THREAD

**Issue by Jayyyy-04** [seungw0n/naver-vaccine-macro#6]
안녕하세요 
우선 생업에 종사하심에도 불구하고 타인을 위하여 좋은 프로그램을 제작해주셔서 감사합니다.

늦은 시간에 다운받게 되어 구동 테스트만 해보고 예약시도까지는 해보지 못하였습니다.

테스트를 하면서 수차례 종료와 실행을 반복하게 되었는데 로그인 유지를 눌렀음에도 불구하고 매 번 로그인을 요구하며 네이버 인증서도 매 번 요구하는 상황입니다. 이것을 혹시 해결하여 매 번 같은 브라우저 환경일 수는 없을까요?
답변 미리 감사드립니다 :)

**Comment by seungw0n** [comment]
안녕하세요, 반갑습니다!

일단! 저는 현재 사회복무요원으로 복무 중입니다 :( 

바로 본론에 넘어가서, 이 프로그램은 Selenium 을 사용하고 있습니다 그리고 Selenium Chrome driver 자체 새로운 chrome 프로세스를 생성합니다. 따라서 테스트를 하실 때 프로세스 실행, 종료를 반복하시면 당연하게도 네이버 로그인을 계속 해주셔야합니다.

물론 코드 업데이트 작업을 통해 로그인 정보를 개인 컴퓨터에 저장 시킬 수는 있습니다만 아직 이 부분에 대해서는 계획이 없습니다. 일단 우선적으로 프로그램 안정화와 최적화 그리고 더 나은 로직에 중점을 두고 있기 때문입니다. 

도움이 안된 것 같아 죄송합니다.

혹여라도 궁금하신 점이 있다면 comment 주세요. 

감사합니다!

**Comment by Jayyyy-04** [comment]
늦은 시간에도 답변 달아주셔서 감사합니다!
도움이 안되셨다고 말씀하시니 괜히 죄송해지는 밤이네요 T.T
다행히도 말씀해주신 부분에서 힌트를 얻어 자동 로그인까지는 구현하였습니다! 훌륭한 프로그램 및 답변 감사합니다^^

저는 외부에서 모바일 팀뷰어를 통하여 구동을 하는데 팀뷰어를 통하여 네이버에 로그인하면 캡차에 걸리게 되더라구요...ㅜㅜ test해보니 Chrome driver상에서도 팀뷰어를 통하여 로그인하게 되면 캡차에 걸리게 되어 여쭤보았던 것인데 말씀해주신 부분에서 힌트 얻어 자체적으로 자동 로그인까지 구현하였고 팀뷰어 상으로도 정상 로그인 되는것 확인하였습니다! 다시 한 번 좋은 프로그램 만들어주심에 감사드리고 편안한 밤 되시길 바라겠습니다!
