### ISSUE TITLE
실행방법 문의드립니다.

### ISSUE THREAD

**Issue by hwile** [seungw0n/naver-vaccine-macro#9]
![image](https://user-images.githubusercontent.com/87679310/126856300-a5bce037-3dfe-4f45-81be-3876ab9517f5.png)

안녕하세요, selenium 설치까지했는데.. 실행이 되지 않아 문의드립니다. 
(해당 쪽에 문외한이라 기초적인 내용을 질의 드리는점 양해부탁드립니다.)

setup.py 를 run 해도 작동이 안되는데... 놓친 부분이 있을까요?

**Comment by seungw0n** [comment]
안녕하세요! 넵! 놓치신 부분이 있습니다.

python interpreter 세팅을 안하신 것 같습니다.
다음과 같이 해보세요!
https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#add-existing-interpreter
